---
# Setup LAMP Stack
- hosts: newhost
  tasks:
    - name: install lamp stack
      become: yes
      become_user: root
      yum:
        pkg:
          - httpd
          - php72
        state: present
        update_cache: yes

    - name: service httpd start
      become: yes
      become_user: root
      service:
        name: httpd
        state: started
        enabled: yes

    - name: service mysql start
      become: yes
      become_user: root
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create target directory
      file: path=/var/www/html state=directory mode=0755

    - name: deploy index.html
      become: yes
      become_user: root
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
